defaults:
  - model: 1GB
  - read-method: torch-load
  - _self_

blob:
  account: azstoragetorchdev
  container: models
  sas-env-var: AZURE_STORAGE_SAS_TOKEN

num-runs: 1
max-concurrency: 8
connection-data-block-size: 65536
partition-threshold: 4194304
partition-size: 8388608

hydra:
  sweeper:
    params:
      num-runs: 10
      read-method: torch-load,readall
      model: 100KB,100MB,1GB,50GB
      ++max-concurrency: 4,8,16,32,64,128
#      ++connection-data-block-size: 1024,4096,16384,32768,65536,131072
#      ++partition-threshold: 4194304,16777216,33554432,67108864
#      ++partition-size: 4194304,8388608,16777216,33554432
