defaults:
  - model: 1GB
  - filelike-impl: blobio
  - read-method: torch-load
  - _self_

blob:
  account: azstoragetorchdev
  container: models
  sas-env-var: AZURE_STORAGE_SAS_TOKEN

num-runs: 1

hydra:
  sweeper:
    params:
      filelike-impl: blobio
      num-runs: 10
      read-method: torch-load,readall
      model: 100KB,100MB,1GB,50GB
