defaults:
  - model: 1GB
  - filelike-impl: blobio-generated-sdk
  - read-method: torch-load
  - _self_

blob:
  account: azstoragetorchdev
  container: models
  sas-env-var: AZURE_STORAGE_SAS_TOKEN

num-runs: 1

hydra:
  sweeper:
    params:
      filelike-impl: open,bytesio,blobio-sdk,blobio-generated-sdk,blobio-urllib3,blobio-async,blobio-process,adlfs,blobfile
      num-runs: 10
      read-method: torch-load,readall
      model: 100KB,100MB,1GB,50GB
